export const languages = [
  ['ar', 'العربية'], ['en', 'English'], ['tr', 'Türkçe'], ['fr', 'Français'],
  ['es', 'Español'], ['de', 'Deutsch'], ['pt', 'Português'], ['it', 'Italiano'],
  ['zh', '中文'], ['ja', '日本語'], ['ko', '한국어'], ['ru', 'Русский'],
  ['hi', 'हिन्दी'], ['id', 'Bahasa Indonesia'],
] as const;

export type LanguageCode = typeof languages[number][0];

type Dictionary = Record<string, string>;

const base: Dictionary = {
  overview: 'Overview', intelligence: 'Intelligence', customers: 'Customers', projects: 'Projects', people: 'People', finance: 'Finance', automations: 'Automations', knowledge: 'Knowledge', reports: 'Reports',
  settings: 'Settings', help: 'Academy & Help', search: 'Search your company...', notifications: 'Company notifications', ask: 'Ask BIZMATE', language: 'Language',
  livePulse: 'LIVE BUSINESS PULSE', welcome: 'Welcome back, {name}.', businessHealth: 'Business Health', pipeline: 'Pipeline Value', activeCustomers: 'Active Customers', projectsRisk: 'Projects at Risk',
  attention: 'What needs your attention', activity: 'Company activity', noAlerts: 'No new company alerts', projectsTitle: 'Projects', intelligenceTitle: 'BIZMATE Intelligence', intelligenceText: 'Understand what is happening, why it matters, and what to do next.',
  openIntelligence: 'Open Intelligence →', copilot: 'Your business copilot', prompt: 'Ask BIZMATE...', send: 'Send', close: 'Close', company: 'Company', role: 'Role', global: 'Global', healthy: 'Healthy', needsAttention: 'Needs attention', onTrack: 'On track', addCustomers: 'Add customers', companyScoped: 'Company-scoped', retry: 'Retry →', returnHome: 'Return to BIZMATE',
};

const dictionaries: Record<LanguageCode, Dictionary> = {
  en: base,
  ar: { ...base, overview: 'نظرة عامة', intelligence: 'الذكاء', customers: 'العملاء', projects: 'المشاريع', people: 'الموظفون', finance: 'المالية', automations: 'الأتمتة', knowledge: 'المعرفة', reports: 'التقارير', settings: 'الإعدادات', help: 'الأكاديمية والمساعدة', search: 'ابحث في شركتك...', notifications: 'إشعارات الشركة', ask: 'اسأل BIZMATE', language: 'اللغة', livePulse: 'نبض الأعمال المباشر', welcome: 'مرحباً بعودتك، {name}.', businessHealth: 'صحة الأعمال', pipeline: 'قيمة المبيعات المتوقعة', activeCustomers: 'العملاء النشطون', projectsRisk: 'مشاريع معرضة للخطر', attention: 'ما يحتاج إلى انتباهك', activity: 'نشاط الشركة', noAlerts: 'لا توجد تنبيهات جديدة', projectsTitle: 'المشاريع', intelligenceTitle: 'ذكاء BIZMATE', intelligenceText: 'افهم ما يحدث، ولماذا يهم، وما الخطوة الأفضل التالية.', openIntelligence: 'افتح الذكاء ←', copilot: 'مساعد الأعمال الذكي', prompt: 'اسأل BIZMATE...', send: 'إرسال', close: 'إغلاق', company: 'الشركة', role: 'الدور', global: 'عالمي', healthy: 'جيد', needsAttention: 'يحتاج انتباه', onTrack: 'على المسار', addCustomers: 'أضف عملاء', companyScoped: 'خاص بالشركة', retry: 'إعادة المحاولة ←', returnHome: 'العودة إلى BIZMATE' },
  tr: { ...base, overview: 'Genel Bakış', intelligence: 'Zekâ', customers: 'Müşteriler', projects: 'Projeler', people: 'Ekip', finance: 'Finans', automations: 'Otomasyonlar', knowledge: 'Bilgi', reports: 'Raporlar', settings: 'Ayarlar', help: 'Akademi ve Yardım', search: 'Şirketinizde ara...', notifications: 'Şirket bildirimleri', ask: 'BIZMATE’e Sor', language: 'Dil', livePulse: 'CANLI İŞ NABZI', welcome: 'Tekrar hoş geldin, {name}.', businessHealth: 'İş Sağlığı', pipeline: 'Satış Hattı Değeri', activeCustomers: 'Aktif Müşteriler', projectsRisk: 'Riskli Projeler', attention: 'Dikkat Gerekenler', activity: 'Şirket Aktivitesi', noAlerts: 'Yeni şirket uyarısı yok', projectsTitle: 'Projeler', intelligenceTitle: 'BIZMATE Zekâ', intelligenceText: 'Ne olduğunu, neden önemli olduğunu ve sıradaki en iyi adımı anlayın.', openIntelligence: 'Zekâyı Aç →', copilot: 'İş yardımcınız', prompt: 'BIZMATE’e sorun...', send: 'Gönder', close: 'Kapat', company: 'Şirket', role: 'Rol', global: 'Global', healthy: 'Sağlıklı', needsAttention: 'Dikkat gerekli', onTrack: 'Yolunda', addCustomers: 'Müşteri ekle', companyScoped: 'Şirkete özel', retry: 'Tekrar dene →', returnHome: 'BIZMATE’e dön' },
  fr: { ...base, overview: 'Vue d’ensemble', intelligence: 'Intelligence', customers: 'Clients', projects: 'Projets', people: 'Équipe', finance: 'Finance', automations: 'Automatisations', knowledge: 'Connaissances', reports: 'Rapports', settings: 'Paramètres', help: 'Académie et aide', search: 'Rechercher dans votre entreprise...', notifications: 'Notifications de l’entreprise', ask: 'Demander à BIZMATE', language: 'Langue', livePulse: 'POULS BUSINESS EN DIRECT', welcome: 'Bon retour, {name}.', businessHealth: 'Santé de l’entreprise', pipeline: 'Valeur du pipeline', activeCustomers: 'Clients actifs', projectsRisk: 'Projets à risque', attention: 'À votre attention', activity: 'Activité de l’entreprise', noAlerts: 'Aucune nouvelle alerte', projectsTitle: 'Projets', intelligenceTitle: 'Intelligence BIZMATE', intelligenceText: 'Comprenez ce qui se passe, pourquoi c’est important et quoi faire ensuite.', openIntelligence: 'Ouvrir Intelligence →', copilot: 'Votre copilote business', prompt: 'Demandez à BIZMATE...', send: 'Envoyer', close: 'Fermer', company: 'Entreprise', role: 'Rôle', global: 'Global', healthy: 'Saine', needsAttention: 'Attention requise', onTrack: 'En bonne voie', addCustomers: 'Ajouter des clients', companyScoped: 'Spécifique à l’entreprise', retry: 'Réessayer →', returnHome: 'Retour à BIZMATE' },
  es: { ...base, overview: 'Resumen', intelligence: 'Inteligencia', customers: 'Clientes', projects: 'Proyectos', people: 'Personas', finance: 'Finanzas', automations: 'Automatizaciones', knowledge: 'Conocimiento', reports: 'Informes', settings: 'Ajustes', help: 'Academia y ayuda', search: 'Buscar en tu empresa...', notifications: 'Notificaciones de la empresa', ask: 'Preguntar a BIZMATE', language: 'Idioma', livePulse: 'PULSO EMPRESARIAL EN VIVO', welcome: 'Bienvenido de nuevo, {name}.', businessHealth: 'Salud del negocio', pipeline: 'Valor del pipeline', activeCustomers: 'Clientes activos', projectsRisk: 'Proyectos en riesgo', attention: 'Lo que requiere tu atención', activity: 'Actividad de la empresa', noAlerts: 'No hay alertas nuevas', projectsTitle: 'Proyectos', intelligenceTitle: 'Inteligencia BIZMATE', intelligenceText: 'Entiende qué ocurre, por qué importa y cuál es el siguiente paso.', openIntelligence: 'Abrir Inteligencia →', copilot: 'Tu copiloto empresarial', prompt: 'Pregunta a BIZMATE...', send: 'Enviar', close: 'Cerrar', company: 'Empresa', role: 'Rol', global: 'Global', healthy: 'Saludable', needsAttention: 'Requiere atención', onTrack: 'En curso', addCustomers: 'Añadir clientes', companyScoped: 'Limitado a la empresa', retry: 'Reintentar →', returnHome: 'Volver a BIZMATE' },
  de: { ...base, overview: 'Übersicht', intelligence: 'Intelligenz', customers: 'Kunden', projects: 'Projekte', people: 'Mitarbeiter', finance: 'Finanzen', automations: 'Automatisierung', knowledge: 'Wissen', reports: 'Berichte', settings: 'Einstellungen', help: 'Academy & Hilfe', search: 'Unternehmen durchsuchen...', notifications: 'Unternehmensbenachrichtigungen', ask: 'BIZMATE fragen', language: 'Sprache', livePulse: 'LIVE-GESCHÄFTSSTATUS', welcome: 'Willkommen zurück, {name}.', businessHealth: 'Geschäftsgesundheit', pipeline: 'Pipeline-Wert', activeCustomers: 'Aktive Kunden', projectsRisk: 'Gefährdete Projekte', attention: 'Ihre Aufmerksamkeit', activity: 'Unternehmensaktivität', noAlerts: 'Keine neuen Warnungen', projectsTitle: 'Projekte', intelligenceTitle: 'BIZMATE Intelligence', intelligenceText: 'Verstehen Sie, was passiert, warum es wichtig ist und was als Nächstes zu tun ist.', openIntelligence: 'Intelligence öffnen →', copilot: 'Ihr Business-Copilot', prompt: 'BIZMATE fragen...', send: 'Senden', close: 'Schließen', company: 'Unternehmen', role: 'Rolle', global: 'Global', healthy: 'Gesund', needsAttention: 'Aufmerksamkeit nötig', onTrack: 'Im Plan', addCustomers: 'Kunden hinzufügen', companyScoped: 'Unternehmensbezogen', retry: 'Erneut versuchen →', returnHome: 'Zurück zu BIZMATE' },
  pt: { ...base, overview: 'Visão geral', intelligence: 'Inteligência', customers: 'Clientes', projects: 'Projetos', people: 'Pessoas', finance: 'Finanças', automations: 'Automações', knowledge: 'Conhecimento', reports: 'Relatórios', settings: 'Configurações', help: 'Academia e ajuda', search: 'Pesquisar na empresa...', notifications: 'Notificações da empresa', ask: 'Perguntar ao BIZMATE', language: 'Idioma', livePulse: 'PULSO DE NEGÓCIOS AO VIVO', welcome: 'Bem-vindo de volta, {name}.', businessHealth: 'Saúde do negócio', pipeline: 'Valor do pipeline', activeCustomers: 'Clientes ativos', projectsRisk: 'Projetos em risco', attention: 'O que requer atenção', activity: 'Atividade da empresa', noAlerts: 'Nenhum alerta novo', projectsTitle: 'Projetos', intelligenceTitle: 'Inteligência BIZMATE', intelligenceText: 'Entenda o que acontece, por que importa e qual é o próximo passo.', openIntelligence: 'Abrir Inteligência →', copilot: 'Seu copiloto empresarial', prompt: 'Pergunte ao BIZMATE...', send: 'Enviar', close: 'Fechar', company: 'Empresa', role: 'Função', global: 'Global', healthy: 'Saudável', needsAttention: 'Requer atenção', onTrack: 'No caminho', addCustomers: 'Adicionar clientes', companyScoped: 'Exclusivo da empresa', retry: 'Tentar novamente →', returnHome: 'Voltar ao BIZMATE' },
  it: base, zh: base, ja: base, ko: base, ru: base, hi: base, id: base,
};

export function getDictionary(language: LanguageCode): Dictionary { return dictionaries[language] || base; }
export function isRtl(language: LanguageCode) { return language === 'ar'; }
export function interpolate(text: string, values: Record<string, string>) { return text.replace(/\{(\w+)\}/g, (_, key) => values[key] ?? ''); }
