'use client';

import '../module.css';
import { FormEvent, useEffect, useState } from 'react';
import { onAuthStateChanged, type User } from 'firebase/auth';
import { doc, getDoc, updateDoc } from 'firebase/firestore';
import { getFirebaseAuth } from '@/lib/firebase-auth';
import { getFirebaseDb } from '@/lib/firebase-db';
import { canManageCompanySettings } from '@/lib/permissions';
import type { UserRole } from '@/types/business';

export default function SettingsPage() {
  const [user,setUser]=useState<User|null>(null); const [role,setRole]=useState<UserRole|null>(null); const [orgId,setOrgId]=useState(''); const [form,setForm]=useState({name:'',industry:'',country:'',currency:'USD',timezone:'UTC',locale:'en-US'}); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('');
  useEffect(()=>onAuthStateChanged(getFirebaseAuth(),setUser),[]);
  useEffect(()=>{let cancelled=false; async function load(){if(!user)return;try{const db=getFirebaseDb();const profile=await getDoc(doc(db,'users',user.uid));const id=String(profile.data()?.organizationId??'');if(!id)throw new Error('Your account is not connected to a company workspace.');const member=await getDoc(doc(db,'organizations',id,'members',user.uid));const raw=String(member.data()?.role??'employee');const r:UserRole=['owner','admin','manager','employee'].includes(raw)?raw as UserRole:'employee';const org=await getDoc(doc(db,'organizations',id));if(!org.exists())throw new Error('Company workspace was not found.');const d=org.data();if(!cancelled){setOrgId(id);setRole(r);setForm({name:String(d.name??''),industry:String(d.industry??''),country:String(d.country??''),currency:String(d.currency??'USD'),timezone:String(d.timezone??'UTC'),locale:String(d.locale??'en-US')});}}catch(e){if(!cancelled)setError(e instanceof Error?e.message:'Unable to load settings.');}finally{if(!cancelled)setLoading(false)}}void load();return()=>{cancelled=true}},[user]);
  async function save(e:FormEvent){e.preventDefault();if(!orgId||!role||!canManageCompanySettings(role))return;setSaving(true);setMessage('');setError('');try{await updateDoc(doc(getFirebaseDb(),'organizations',orgId),{name:form.name.trim(),industry:form.industry.trim(),country:form.country.trim(),currency:form.currency,timezone:form.timezone,locale:form.locale,updatedAt:new Date()});window.localStorage.setItem('bizmate:organization',orgId);setMessage('Company settings saved successfully.');}catch(e){setError(e instanceof Error?e.message:'Unable to save settings.');}finally{setSaving(false)}}
  if(loading)return <main className="module-page"><div className="module-empty"><h1>Loading settings</h1></div></main>;
  if(error&&!orgId)return <main className="module-page"><div className="module-empty"><h1>Settings unavailable</h1><p>{error}</p></div></main>;
  const editable=!!role&&canManageCompanySettings(role);
  return <main className="module-page"><header><div><small>BIZMATE / SETTINGS</small><h1>Company settings</h1><p>Manage the real identity and regional configuration of your company workspace.</p></div></header>{message&&<div className="module-success">{message}</div>}{error&&<div className="module-error">{error}</div>}<form className="settings-grid" onSubmit={save}><section className="data-card settings-card"><div className="data-head"><h2>Company identity</h2><span>{role}</span></div><label>Company name<input disabled={!editable} required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Industry<input disabled={!editable} value={form.industry} onChange={e=>setForm({...form,industry:e.target.value})} placeholder="Technology, Retail, Finance..."/></label><label>Country<input disabled={!editable} value={form.country} onChange={e=>setForm({...form,country:e.target.value})}/></label></section><section className="data-card settings-card"><div className="data-head"><h2>Regional settings</h2><span>Workspace</span></div><label>Currency<select disabled={!editable} value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}><option>USD</option><option>EUR</option><option>GBP</option><option>TRY</option><option>SAR</option><option>AED</option></select></label><label>Timezone<select disabled={!editable} value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})}><option>UTC</option><option>Europe/Istanbul</option><option>Europe/London</option><option>Europe/Berlin</option><option>America/New_York</option><option>Asia/Dubai</option></select></label><label>Locale<select disabled={!editable} value={form.locale} onChange={e=>setForm({...form,locale:e.target.value})}><option>en-US</option><option>ar</option><option>tr-TR</option><option>de-DE</option><option>fr-FR</option></select></label></section><div className="settings-actions">{editable?<button className="primary" disabled={saving} type="submit">{saving?'Saving...':'Save company settings →'}</button>:<p>Only owners and admins can change company settings.</p>}</div></form></main>;
}
