'use client';

import '../module.css';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { onAuthStateChanged, type User } from 'firebase/auth';
import { doc, getDoc } from 'firebase/firestore';
import { getFirebaseAuth } from '@/lib/firebase-auth';
import { getFirebaseDb } from '@/lib/firebase-db';
import { createOrgRecord, listOrgRecords, updateOrgRecord } from '@/lib/firestore-service';

type Workflow = { id: string; name: string; trigger: string; actions: number; actionType?: 'create_activity' | 'create_approval'; status: 'active' | 'paused' | 'approval required' };

export default function AutomationsPage() {
  const [user, setUser] = useState<User | null>(null); const [orgId, setOrgId] = useState(''); const [workflows, setWorkflows] = useState<Workflow[]>([]); const [loading, setLoading] = useState(true); const [show, setShow] = useState(false); const [name, setName] = useState(''); const [trigger, setTrigger] = useState('Customer created'); const [actionType, setActionType] = useState<Workflow['actionType']>('create_activity'); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => onAuthStateChanged(getFirebaseAuth(), setUser), []);
  useEffect(() => { let cancelled=false; async function load(){ if(!user)return; try { const profile=await getDoc(doc(getFirebaseDb(),'users',user.uid)); const id=String(profile.data()?.organizationId??''); if(!id)throw new Error('Your account is not connected to a company workspace.'); const rows=await listOrgRecords<Workflow>(id,'automations'); if(!cancelled){setOrgId(id);setWorkflows(rows);}} catch(e){if(!cancelled)setError(e instanceof Error?e.message:'Unable to load automations.');} finally{if(!cancelled)setLoading(false);} } void load(); return()=>{cancelled=true}; },[user]);
  const active=useMemo(()=>workflows.filter(w=>w.status==='active').length,[workflows]);
  async function createWorkflow(e:FormEvent){e.preventDefault();if(!orgId||!name.trim())return;setSaving(true);try{const data={name:name.trim(),trigger,actions:1,actionType,status:'active' as const};const id=await createOrgRecord(orgId,'automations',data);setWorkflows(w=>[{id,...data},...w]);setName('');setShow(false);}catch(e){setError(e instanceof Error?e.message:'Unable to create workflow.');}finally{setSaving(false)}}
  async function toggle(w:Workflow){try{const status=w.status==='active'?'paused':'active';await updateOrgRecord(orgId,'automations',w.id,{status});setWorkflows(rows=>rows.map(x=>x.id===w.id?{...x,status}:x));}catch(e){setError(e instanceof Error?e.message:'Unable to update workflow.');}}
  if(loading)return <main className="module-page"><div className="module-empty"><h1>Loading automations</h1></div></main>;
  return <main className="module-page"><header><div><small>BIZMATE / AUTOMATIONS</small><h1>Automations</h1><p>Active workflows execute immediately when their matching business event occurs.</p></div><button className="primary" onClick={()=>setShow(true)}>+ New workflow</button></header>{error&&<div className="module-error">{error}</div>}<section className="summary-row"><div><span>Active workflows</span><strong>{active}</strong></div><div><span>Total workflows</span><strong>{workflows.length}</strong></div><div><span>Execution mode</span><strong>REAL-TIME</strong></div></section><section className="data-card"><div className="data-head"><h2>Workflow library</h2></div><div className="table"><div className="tr th"><span>Workflow</span><span>Trigger</span><span>Action</span><span>Status</span></div>{workflows.map(w=><div className="tr" key={w.id}><span><b>{w.name}</b><small>Company automation</small></span><span>{w.trigger}</span><span>{w.actionType==='create_approval'?'Approval request':'Activity record'}</span><span><button className="ghost" onClick={()=>void toggle(w)}>{w.status}</button></span></div>)}{!workflows.length&&<div className="module-empty compact"><h3>No workflows yet</h3><p>Create an automation and it will execute when its trigger occurs.</p></div>}</div></section>{show&&<div className="module-overlay" onClick={()=>!saving&&setShow(false)}><form className="module-modal" onSubmit={createWorkflow} onClick={e=>e.stopPropagation()}><button type="button" className="modal-close" onClick={()=>!saving&&setShow(false)}>×</button><small>BIZMATE / AUTOMATION</small><h2>New workflow</h2><label>Workflow name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. New lead follow-up"/></label><label>Trigger<select value={trigger} onChange={e=>setTrigger(e.target.value)}><option>Customer created</option><option>Project becomes at-risk</option><option>Expense requires approval</option><option>Manual trigger</option></select></label><label>Action<select value={actionType} onChange={e=>setActionType(e.target.value as Workflow['actionType'])}><option value="create_activity">Create activity record</option><option value="create_approval">Create approval request</option></select></label><p>Automations run in the signed-in company workspace after the matching event is saved.</p><button className="primary" disabled={saving} type="submit">{saving?'Saving...':'Create workflow →'}</button></form></div>}</main>;
}
